#!/bin/sh
# download and scan a single github repo's master branch, output to stdout
if [ -z $1 ]; then
    echo "$0 <https://github/repo/url>"
    exit 2
fi
url=$1
echo "Scanning $url!"
mkdir -p churn
cd churn
git clone $url
graudit -x *.js,*.json,*.map,*.sql -d ./flatline.db .
