unserialize[[:space:]]*\(.*\$
file_exists[[:space:]]*\(.*\$
md5_file[[:space:]]*\(.*\$
filemtime[[:space:]]*\(.*\$
filesize[[:space:]]*\(.*\$
file_get_contents[[:space:]]*\(.*\$
fopen[[:space:]]*\(.*\$
file[[:space:]]*\(.*\$
php://stdin
php://stdout
php://stderr
php://output
php://input
php://filter
php://memory
php://temp
phar://.*\$
expect:// 
