.\"
.\" (C) Copyletft Eldar "Wireghoul" Marcussen - http://www.justanotherhacker.com.
.\"
.\" See mdoc(7) for further reference.
.\"
.Dd $Mdocdate: June 3 2010 $
.Dt MANUALS 7
.Os
.Sh NAME
.\"
.Nm graudit signatures
.Nd syntax and composition
.\"
.Sh DESCRIPTION
.\"
.Em graudit is only as good as the signature database.
.Pp
iblahblahblahblah
blahblhablhablhablhablhab
